// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_WEB_API_KEY'),
    appId: '1:50319752694:web:411372af70fa7070121bd7',
    messagingSenderId: '50319752694',
    projectId: 'elmasroof-5c89a',
    authDomain: 'elmasroof-5c89a.firebaseapp.com',
    databaseURL: 'https://elmasroof-5c89a-default-rtdb.firebaseio.com',
    storageBucket: 'elmasroof-5c89a.firebasestorage.app',
    measurementId: 'G-RRBDN8Y9SD',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_ANDROID_API_KEY'),
    appId: '1:50319752694:android:a6b7a1c249cabaf8121bd7',
    messagingSenderId: '50319752694',
    projectId: 'elmasroof-5c89a',
    databaseURL: 'https://elmasroof-5c89a-default-rtdb.firebaseio.com',
    storageBucket: 'elmasroof-5c89a.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_IOS_API_KEY'),
    appId: '1:50319752694:ios:3db08027469323c1121bd7',
    messagingSenderId: '50319752694',
    projectId: 'elmasroof-5c89a',
    databaseURL: 'https://elmasroof-5c89a-default-rtdb.firebaseio.com',
    storageBucket: 'elmasroof-5c89a.firebasestorage.app',
    iosClientId: '50319752694-j6j61b4qessls7vbf1njtct4etqa88u9.apps.googleusercontent.com',
    iosBundleId: 'com.helloworld.elmasroof.elmasroof',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_MACOS_API_KEY'),
    appId: '1:50319752694:ios:3db08027469323c1121bd7',
    messagingSenderId: '50319752694',
    projectId: 'elmasroof-5c89a',
    databaseURL: 'https://elmasroof-5c89a-default-rtdb.firebaseio.com',
    storageBucket: 'elmasroof-5c89a.firebasestorage.app',
    iosClientId: '50319752694-j6j61b4qessls7vbf1njtct4etqa88u9.apps.googleusercontent.com',
    iosBundleId: 'com.helloworld.elmasroof.elmasroof',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_WINDOWS_API_KEY'),
    appId: '1:50319752694:web:c414e81ceca743d3121bd7',
    messagingSenderId: '50319752694',
    projectId: 'elmasroof-5c89a',
    authDomain: 'elmasroof-5c89a.firebaseapp.com',
    databaseURL: 'https://elmasroof-5c89a-default-rtdb.firebaseio.com',
    storageBucket: 'elmasroof-5c89a.firebasestorage.app',
    measurementId: 'G-RE5NC8WNLC',
  );
}
